name: Cloudflare RDP Setup

on: 
  workflow_dispatch

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Download Cloudflare Tunnel Binary
      run: |
        Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe
        Move-Item -Path "cloudflared.exe" -Destination "C:\Windows\System32\cloudflared.exe"

    - name: Authenticate Cloudflare Tunnel
      run: |
        cloudflared tunnel login
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

    - name: Create Tunnel Config
      run: |
        New-Item -ItemType Directory -Path "$env:USERPROFILE\.cloudflared"
        Set-Content -Path "$env:USERPROFILE\.cloudflared\config.yml" -Value @"
        tunnel: my-rdp-tunnel
        credentials-file: C:\Windows\System32\.cloudflared\cert.pem
        ingress:
          - hostname: your-subdomain.yourdomain.com
            service: rdp://localhost:3389
          - service: http_status:404
        "@

    - name: Start Cloudflare Tunnel
      run: |
        cloudflared tunnel --config C:\Windows\System32\.cloudflared\config.yml --no-autoupdate

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Confirm RDP Status
      run: |
        Get-NetFirewallRule -DisplayGroup "Remote Desktop" | Select-Object DisplayName, Enabled
